include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/core/l10n/gen/**

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    require_trailing_commas: true
    avoid_print: true
